version: '2.0'
services:
  <%= name %>:
    build:
      context: .
      dockerfile: Dockerfile
    image: <%= name %>
    command: npm start
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/bower_components
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development